version: "2"
services:
  carbon:
    build:
      context: ./carbon
      dockerfile: Dockerfile
    command: -config=carbon.conf
    restart: always
    expose:
      - 2003/udp
      - 2003
      - 2004
      - 8080
      - 7007
      - 7002
    volumes:
      - carbon:/data/graphite/whisper/
# due to annotations feature in sitespeed.io we have to use real graphite
# which supports annotations storage in local db (SQLite)
# otherwise, carbonapi serves as drop-in replacement for graphite-web
#  carbonapi:
#    build:
#      context: ./carbonapi
#      dockerfile: Dockerfile
#    command: -stdout -z http://carbon:8080
#    restart: always
#    expose:
#      - 8080
#    depends_on:
#      - carbon
  graphite-web:
    build:
      context: ./graphite-web
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - carbon
    volumes:
      - graphite:/opt/graphite/storage
  grafana:
    image: grafana/grafana:4.2.0
    ports:
      - 3000:3000
    restart: always
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=test
      - GF_SECURITY_ADMIN_USER=test
    depends_on:
      - graphite-web
    volumes:
      - grafana:/var/lib/grafana
  grafana-setup:
    image: sitespeedio/grafana-bootstrap:sitespeed.io-4.6
    environment:
      - GF_PASSWORD=test
      - GF_USER=test
    depends_on:
      - grafana
  sitespeed.io:
    image: sitespeedio/sitespeed.io:4.7.0
    command: -V
    privileged: true
    shm_size: 1g
    volumes:
      - ./sitespeed-result/:/sitespeed.io/sitespeed-result
      - ./urls.txt/:/sitespeed.io/urls.txt
volumes:
  grafana:
  graphite:
  carbon:
